//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnipeLabelEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnipeLabelEditor.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the SnipeLabelEditor you can easily create labels with HTML and CSS and have them output as PDF. Through the connection to the Snipe API you can work with variables, which are automatically replaced when rendering the PDF. It is also possible to create barcodes and QR codes. Have fun designing..
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset-Id.
        /// </summary>
        internal static string assetId {
            get {
                return ResourceManager.GetString("assetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer-Token.
        /// </summary>
        internal static string bearerToken {
            get {
                return ResourceManager.GetString("bearerToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and edit.
        /// </summary>
        internal static string copyAndEdit {
            get {
                return ResourceManager.GetString("copyAndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a sample asset to view the variable names..
        /// </summary>
        internal static string exampleAssetText {
            get {
                return ResourceManager.GetString("exampleAssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected.
        /// </summary>
        internal static string exportLabels {
            get {
                return ResourceManager.GetString("exportLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate image.
        /// </summary>
        internal static string generateImage {
            get {
                return ResourceManager.GetString("generateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF.
        /// </summary>
        internal static string generatePdf {
            get {
                return ResourceManager.GetString("generatePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The labels could not be imported:.
        /// </summary>
        internal static string importFailed {
            get {
                return ResourceManager.GetString("importFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        internal static string importLabels {
            get {
                return ResourceManager.GetString("importLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following labels were successfully imported:.
        /// </summary>
        internal static string importSucceeded {
            get {
                return ResourceManager.GetString("importSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Editor.
        /// </summary>
        internal static string labelEditor {
            get {
                return ResourceManager.GetString("labelEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Label does not exist..
        /// </summary>
        internal static string labelNotExist {
            get {
                return ResourceManager.GetString("labelNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string labels {
            get {
                return ResourceManager.GetString("labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin bottom.
        /// </summary>
        internal static string marginBottom {
            get {
                return ResourceManager.GetString("marginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin left.
        /// </summary>
        internal static string marginLeft {
            get {
                return ResourceManager.GetString("marginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin right.
        /// </summary>
        internal static string marginRight {
            get {
                return ResourceManager.GetString("marginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin top.
        /// </summary>
        internal static string marginTop {
            get {
                return ResourceManager.GetString("marginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a name for your label..
        /// </summary>
        internal static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string printView {
            get {
                return ResourceManager.GetString("printView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload label.
        /// </summary>
        internal static string reloadLabel {
            get {
                return ResourceManager.GetString("reloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the label {0}?.
        /// </summary>
        internal static string requestLabelDelete {
            get {
                return ResourceManager.GetString("requestLabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved!.
        /// </summary>
        internal static string settingsSaved {
            get {
                return ResourceManager.GetString("settingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnipeAPI Base-URL.
        /// </summary>
        internal static string sinpeItBaseUrl {
            get {
                return ResourceManager.GetString("sinpeItBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
